name: CsWin32Ex CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/assets/**'
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/assets/**'
      - 'docs/**'
      - '*.md'

permissions:
  actions: read
  checks: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Build the solution
      run: dotnet build

    - name: Run the tests
      run: dotnet test --no-build --logger "trx"

    - name: Report the test results
      uses: dorny/test-reporter@v2
      with:
        name: Test summary
        path: "**/*.trx"
        reporter: dotnet-trx
        use-actions-summary: 'true'
        list-suites: 'failed'
        list-tests: 'failed'
