name: CsWin32Ex CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: read
  checks: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Build the solution
      run: dotnet build

    - name: Run the tests
      run: dotnet test

    - name: Report the test results
      uses: dorny/test-reporter@v1
      with:
        name: Summary Tests
        path: "**/*.trx"
        reporter: dotnet-trx
        only-summary: true
        list-suites: 'failed'
        list-tests: 'failed'
