trigger:
  batch: true
  branches:
    include:
    - main
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
schedules:
- cron: "0 3 * * *" # Daily @ 8 PM PST
  displayName: Daily build
  branches:
    include:
    - main

parameters:
- name: SignSelection
  displayName: Sign?
  type: boolean
  default: false
- name: includeMacOS
  displayName: Build on macOS
  type: boolean
  default: false # macOS is often bogged down in Azure Pipelines
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true

stages:

- stage: Build
  variables:
    TreatWarningsAsErrors: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    BuildConfiguration: Release
    BuildPlatform: Any CPU
    NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages/
    SignSelection: ${{ parameters.SignSelection }}

  jobs:
  - template: build.yml
    parameters:
      includeMacOS: ${{ parameters.includeMacOS }}
      RunTests: ${{ parameters.RunTests }}

- stage: azure_public_winsdk_feed
  displayName: azure-public/winsdk feed
  condition: and(succeeded(), eq(dependencies.Build.outputs['Windows.SetPipelineVariables.IsSigned'], 'true'))
  jobs:
  - job: push
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: none
    - download: current
      artifact: deployables-Windows
      displayName: Download deployables-Windows artifact
    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        packageType: sdk
        version: 6.x
    - task: NuGetAuthenticate@0
      displayName: Authenticate NuGet feeds
      inputs:
        nuGetServiceConnections: azure-public/winsdk
        forceReinstallCredentialProvider: true
    - script: dotnet nuget push $(Pipeline.Workspace)/deployables-Windows/*.nupkg -s https://pkgs.dev.azure.com/azure-public/winsdk/_packaging/CI/nuget/v3/index.json --api-key azdo --skip-duplicate
