trigger:
  branches:
    include:
    - main
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/

parameters:
- name: SignSelection
  displayName: Sign?
  type: boolean
  default: false
- name: includeMacOS
  displayName: Build on macOS
  type: boolean
  default: false # macOS is often bogged down in Azure Pipelines

stages:

- stage: Build
  variables:
    TreatWarningsAsErrors: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    BuildConfiguration: Release
    BuildPlatform: Any CPU
    push_to_ci: true
    ci_feed: MSFTNuget
    NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
    SignSelection: ${{ parameters.SignSelection }}

  jobs:
  - template: build.yml
    parameters:
      includeMacOS: ${{ parameters.includeMacOS }}
