trigger:
  batch: true
  branches:
    include:
    - main
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
schedules:
- cron: "0 3 * * *" # Daily @ 8 PM PST
  displayName: Daily build
  branches:
    include:
    - main

parameters:
# As an entrypoint pipeline yml file, all parameters here show up in the Queue Run dialog.
# If any paramaters should NOT be queue-time options, they should be removed from here
# and references to them in this file replaced with hard-coded values.
- name: ForceOfficialBuild
  displayName: Official build (sign, compliance, etc.)
  type: boolean
  default: false # this should remain false so PR builds using this pipeline are unofficial
# - name: ShouldSkipOptimize # Uncomment this and references to it below when setting EnableOptProf to true in build.yml.
#   displayName: Skip OptProf optimization
#   type: boolean
#   default: false
- name: EnableMacOSBuild
  displayName: Build on macOS
  type: boolean
  default: false # macOS is often bogged down in Azure Pipelines
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true
- name: EnableAPIScan
  displayName: Include APIScan with compliance tools
  type: boolean
  default: false # enable in individual repos only AFTER updating TSAOptions.json with your own values

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
- template: GlobalVariables.yml

# Pool options are documented at: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/migration/ed-sharedpool
extends:
  ${{ if or(parameters.ForceOfficialBuild, eq(variables['Build.Reason'],'Schedule')) }}:
    template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
    parameters:
      sdl:
        sourceAnalysisPool: Azure-Pipelines-1ESPT-ExDShared
        codeSignValidation:
          enabled: true
          break: false
          additionalTargetsGlobPattern: -|Variables-*\*.ps1;-|APIScanInputs-*\**;-|test_symbols-*\**;-|MicroBuild\**
        policheck:
          enabled: true
          exclusionsFile: $(System.DefaultWorkingDirectory)\azure-pipelines\PoliCheckExclusions.xml
        suppression:
          suppressionFile: $(System.DefaultWorkingDirectory)\azure-pipelines\falsepositives.gdnsuppress
        sbom:
          enabled: true
      stages:
      - stage: Build
        variables:
        - template: /azure-pipelines/BuildStageVariables.yml@self
        jobs:
        - template: /azure-pipelines/build.yml@self
          parameters:
            Is1ESPT: true
            RealSign: true
            # ShouldSkipOptimize: ${{ parameters.ShouldSkipOptimize }}
            EnableAPIScan: ${{ and(parameters.EnableAPIScan, ne(variables['Build.Reason'], 'pullRequest')) }}
            windowsPool: Azure-Pipelines-1ESPT-ExDShared
            linuxPool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: ubuntu-2004
              os: linux
            EnableMacOSBuild: ${{ parameters.EnableMacOSBuild }}
            RunTests: ${{ parameters.RunTests }}
      - template: /azure-pipelines/prepare-insertion-stages.yml@self
        parameters:
          RealSign: true
  ${{ else }}:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
    parameters:
      sdl:
        sourceAnalysisPool: Azure-Pipelines-1ESPT-ExDShared
        suppression:
          suppressionFile: $(System.DefaultWorkingDirectory)\azure-pipelines\falsepositives.gdnsuppress
      stages:
      - stage: Build
        variables:
        - template: /azure-pipelines/BuildStageVariables.yml@self
        jobs:
        - template: /azure-pipelines/build.yml@self
          parameters:
            Is1ESPT: true
            RealSign: false
            # ShouldSkipOptimize: ${{ parameters.ShouldSkipOptimize }}
            EnableAPIScan: false
            windowsPool: Azure-Pipelines-1ESPT-ExDShared
            linuxPool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: ubuntu-2004
              os: linux
            EnableMacOSBuild: ${{ parameters.EnableMacOSBuild }}
            RunTests: ${{ parameters.RunTests }}
      - template: /azure-pipelines/prepare-insertion-stages.yml@self
        parameters:
          RealSign: false
