parameters:
- name: RealSign
  type: boolean
  default: false

stages:

- stage: release
  displayName: Publish
  condition: and(succeeded(), eq('${{ parameters.RealSign }}', 'true'))
  jobs:
  - ${{ if true }}: # leave the condition to avoid merge conflicts later.
    - job: push
      displayName: azure-public/winsdk feed
      pool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: ubuntu-2004
        os: linux
      templateContext:
        outputs:
        - output: nuget
          displayName: 📦 Push nuget packages
          packagesToPush: '$(Pipeline.Workspace)/deployables-Windows/*.nupkg'
          packageParentPath: $(Pipeline.Workspace)/deployables-Windows
          allowPackageConflicts: true
          nuGetFeedType: external
          publishFeedCredentials: azure-public/winsdk
      steps:
      - checkout: none
      - download: current
        artifact: deployables-Windows
        displayName: 🔻 Download deployables-Windows artifact
