steps:
- download: current
  displayName: Download deployables
  artifact: deployables-Windows

- task: NuGetToolInstaller@1
  displayName: Use NuGet 5.x
  inputs:
    versionSpec: 5.x

- task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2 # NuGetCommand
  displayName: Push packages to CI feed
  inputs:
    command: push
    packagesToPush: $(Pipeline.Workspace)/deployables-Windows/NuGet/*.nupkg
    nuGetFeedType: internal
    publishVstsFeed: $(ci_feed)
    allowPackageConflicts: true
  condition: and(succeeded(), eq(variables['push_to_ci'], 'true'), ne(variables['ci_feed'], ''), ne(variables['Build.Reason'], 'PullRequest'))
